### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/demos-for-react#11]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by MidouWebDev** [comment]
@TorstenDittmann @Meldiron I want to work on this
Can you assign me ?

**Comment by christyjacob4** [comment]
@MidouWebDev  All the best :rocket:

**Comment by akashgp09** [comment]
Hi @Meldiron @christyjacob4! I would like to work on it.

**Comment by RiyaGupta89** [comment]
@christyjacob4 Can I raise some issues to start contributing to this project?

**Comment by christyjacob4** [comment]
@RiyaGupta89  Sure, you can raise the issues and the core team can help you decide whether they are relevant for the project. :+1:

**Comment by siddhiiguptaa** [comment]
Issue closed? 🤔 I would love to help incase there is any help needed!

**Comment by christyjacob4** [comment]
@siddhiiguptaa Looks like this issue has already been taken. We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by divshacker** [comment]
May I work on this Issue ?

**Comment by Meldiron** [comment]
@divshacker Looks like you have some issues assigned to you already. We request you to complete those before requesting assignments on new ones. Also, please consider picking a different type of issue so other contributors can try this one.

**Comment by Amnx404** [comment]
Hey can i work on this?

**Comment by lohanidamodar** [comment]
@Amnx404 assigned to you all the best 🚀

**Comment by akashgp09** [comment]
@lohanidamodar there is one PR already raised for this issue https://github.com/appwrite/demos-for-react/pull/13

**Comment by Amnx404** [comment]
@lohanidamodar @akashgp09 Hey since the PR is raised, am i required to do this? Please let me know

**Comment by Meldiron** [comment]
@Amnx404 @akashgp09 Whoops looks like there was a small confusion. In this case, we will accept the first of your PR from @akashgp09.

@Amnx404 We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon!
