### ISSUE TITLE
Needs Clarification

### ISSUE THREAD

**Issue by arpitghura** [appwrite/demos-for-react#18]
Hello team, I would like to know about how I can contribute to this repository as I have knowledge of React and want to implement it somewhere. 
Some questions are there in my mind.
1. Do I need to add examples that include Appwrite integration?
2. Can I add some personal projects that I build during learning that will help other developers in getting started?

**Comment by stnguyen90** [comment]
@arpitghura , yes this repo contains demos of Appwrite + React. If you would like to contribute something, feel free to pitch your idea in https://github.com/appwrite/appwrite/issues/4024 and we'll review your request. For now, I'm going to close this to prevent any additional attention.
